<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite [
        <!ELEMENT suite (test)*>
        <!ATTLIST suite
                thread-count CDATA #REQUIRED
                name CDATA #REQUIRED
                parallel CDATA #REQUIRED>
        <!ELEMENT test (parameter|classes)*>
        <!ATTLIST test
                name CDATA #REQUIRED>
        <!ELEMENT parameter (#PCDATA)>
        <!ATTLIST parameter
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT classes (class)*>
        <!ELEMENT class (#PCDATA)>
        <!ATTLIST class
                name CDATA #REQUIRED>
        ]>
<suite thread-count="300" name="DesktopBrowsers" parallel="tests">
    <test name = "1" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "2" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "3" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "4" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "5" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "6" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "7" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "8" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "9" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "10" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "11" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "12" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "13" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "14" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "15" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "16" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "17" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "18" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "19" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "20" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "21" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "22" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "23" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "24" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "25" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "26" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "27" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "28" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "29" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "30" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "31" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "32" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "33" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "34" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "35" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "36" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "37" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "38" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "39" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "40" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "41" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "42" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "43" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "44" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "45" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "46" >
        <parameter name="browser" value="Chrome"/>
        <parameter name="version" value="91.0"/>
        <parameter name= "platform" value="Windows 10"/>
        <parameter name= "fixedIp" value="10.82.4.230"/>
        <parameter name= "resolution" value="1920x1080"/>
        <parameter name= "timezone" value="UTC+04:00"/>
        <parameter name= "geoLocation" value="IN"/>
        <parameter name= "tunnelName" value="prateekSignh"/>
        <parameter name= "tunnel" value="false"/>
        <classes>
            <class name="magicleapTesting.magicLeap"/>
        </classes>
    </test> <!-- Test -->


    <test name = "47" >
        <parameter name="browser" value="Chrome"/>